### ISSUE TITLE
Publish image dependency update

### ISSUE THREAD

**Issue by kaikalii** [teovoinea/steganography#15]
I see in the commit log that the image crate dependency was upgraded to 0.21.0. Would it be possible to publish this change to crates.io? I am using steganography and image on its own, but the 0.19.0 and 0.21.0 versions of image conflict, so I have to use the old version of image to be compatible with steganography. I'd like to be using the newest version of the crate.

**Comment by teovoinea** [comment]
I pushed the latest code to crates.io as version 1.0.2 😊
